<a href="https://colab.research.google.com/github/sharinair14/Basic-ML-Practice/blob/master/GridsearchCV_with_Digits_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.datasets import load_digits

In [96]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [97]:
df=pd.DataFrame(data=digits.data)

In [98]:
df['target'] = digits.target

In [99]:
df.head()

     0    1    2     3     4     5  ...    59    60    61   62   63  target
0  0.0  0.0  5.0  13.0   9.0   1.0  ...  13.0  10.0   0.0  0.0  0.0       0
1  0.0  0.0  0.0  12.0  13.0   5.0  ...  11.0  16.0  10.0  0.0  0.0       1
2  0.0  0.0  0.0   4.0  15.0  12.0  ...   3.0  11.0  16.0  9.0  0.0       2
3  0.0  0.0  7.0  15.0  13.0   1.0  ...  13.0  13.0   9.0  0.0  0.0       3
4  0.0  0.0  0.0   1.0  11.0   0.0  ...   2.0  16.0   4.0  0.0  0.0       4

[5 rows x 65 columns]

In [100]:
X = df.drop('target',axis=1)
y = df['target']

In [101]:
from sklearn.model_selection import train_test_split

In [111]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [103]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.model_selection import GridSearchCV

In [112]:
model_params = { 'Logistic Regression':{'model':LogisticRegression(solver='liblinear',multi_class='auto'),
                      'params':{'C':[1,3,5,10,50]}},
                'SVM':{'model':SVC(gamma='auto'),
                      'params':{'kernel':['linear','rbf'],'C':[1,10,20,30,50,100]}},
                'Decision Tree':{'model':DecisionTreeClassifier(),
                      'params':{'criterion':['gini','entropy']}},
                'Random Forest':{'model':RandomForestClassifier(),
                      'params':{'n_estimators':[1,5,10,20]}},
                'Naive Bayes Gaussian':{'model':GaussianNB(),
                      'params':{}},
                'Naive Bayes Multinomial':{'model':MultinomialNB(),
                      'params':{}}
    

}

In [113]:
scores = []
for model_name, mp in model_params.items():
  clf = GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
  clf.fit(X_train, y_train)
  scores.append({'Model': model_name,
                 'Best Score':clf.best_score_,
                 'Best Param':clf.best_params_})

In [114]:
df_score=pd.DataFrame(data=scores,columns=['Model','Best Score','Best Param'])
df_score

                     Model  Best Score                    Best Param
0      Logistic Regression    0.958943                      {'C': 1}
1                      SVM    0.982603  {'C': 1, 'kernel': 'linear'}
2            Decision Tree    0.855253      {'criterion': 'entropy'}
3            Random Forest    0.956850          {'n_estimators': 20}
4     Naive Bayes Gaussian    0.859437                            {}
5  Naive Bayes Multinomial    0.899806                            {}

SVM is the best classifier for this Digits dataset with C=1 & kernel=linear.